path="C:/Private/PhD_Publications/Publication_of_Algorithm/Code/TrackingAlgorithm/TrackingAlgorithm/TestData/UnitTestData/interpolatePolarCoordinatesLinear/"

self.loadHostVariable('gradientGlobalSize',path)
self.loadHostVariable('nrOfInterpolationPoints',path)
self.loadHostVariable('nrOfDetectionAngleSteps',path)
self.loadHostVariable('nrOfAnglesToCompare',path)
self.loadDeviceVariable('dev_membranePolarRadius',path)
self.loadDeviceVariable('dev_membranePolarTheta',path)
self.loadDeviceVariable('dev_radialVectors',path)
self.loadDeviceVariable('dev_contourCenter',path)
self.loadDeviceVariable('dev_membraneCoordinatesX',path)
self.loadDeviceVariable('dev_membraneCoordinatesY',path)
self.loadDeviceVariable('dev_interpolatedMembraneCoordinatesX',path)
self.loadDeviceVariable('dev_interpolatedMembraneCoordinatesY',path)
self.loadDeviceVariable('dev_membranePolarRadiusTMP',path)
self.loadDeviceVariable('dev_membranePolarThetaTMP',path)
self.loadDeviceVariable('dev_membranePolarRadiusInterpolation',path)
self.loadDeviceVariable('dev_membranePolarThetaInterpolation',path)
self.loadDeviceVariable('dev_membranePolarRadiusInterpolationTesting',path)
self.loadDeviceVariable('dev_membranePolarThetaInterpolationTesting',path)
self.loadDeviceVariable('dev_interpolationAngles',path)
self.loadDeviceVariable("dev_dbgOut",path)
self.loadDeviceVariable("dev_dbgOut2",path)



self.saveHostVariable("gradientGlobalSize",path)
self.saveHostVariable("nrOfInterpolationPoints",path)
self.saveHostVariable("nrOfDetectionAngleSteps",path)
self.saveHostVariable("nrOfAnglesToCompare",path)
self.saveDeviceVariable("dev_membranePolarRadius",path)
self.saveDeviceVariable("dev_membranePolarTheta",path)
self.saveDeviceVariable("dev_radialVectors",path)
self.saveDeviceVariable("dev_contourCenter",path)
self.saveDeviceVariable("dev_membraneCoordinatesX",path)
self.saveDeviceVariable("dev_membraneCoordinatesY",path)
self.saveDeviceVariable("dev_interpolatedMembraneCoordinatesX",path)
self.saveDeviceVariable("dev_interpolatedMembraneCoordinatesY",path)
self.saveDeviceVariable("dev_membranePolarRadiusTMP",path)
self.saveDeviceVariable("dev_membranePolarThetaTMP",path)
self.saveDeviceVariable("dev_membranePolarRadiusInterpolation",path)
self.saveDeviceVariable("dev_membranePolarThetaInterpolation",path)
self.saveDeviceVariable("dev_membranePolarRadiusInterpolationTesting",path)
self.saveDeviceVariable("dev_membranePolarThetaInterpolationTesting",path)
self.saveDeviceVariable("dev_interpolationAngles",path)
self.saveDeviceVariable("dev_dbgOut",path)
self.saveDeviceVariable("dev_dbgOut2",path)
